Example from http://scikit-image.org/docs/0.7.0/api/skimage.graph.mcp.html#skimage.graph.mcp.route_through_array

In [1]:
import numpy as np
from skimage.graph import route_through_array

In [2]:
image = np.array([[1, 3], [10, 12]])
image

array([[ 1,  3],
       [10, 12]])

In [3]:
# Forbid diagonal steps
route_through_array(image, [0, 0], [1, 1], fully_connected=False)

([(0, 0), (0, 1), (1, 1)], 9.5)

In [4]:
# Now allow diagonal steps: the path goes directly from start to end
route_through_array(image, [0, 0], [1, 1])

([(0, 0), (1, 1)], 9.19238815542512)

In [5]:
# Cost is the sum of array values along the path (16 = 1 + 3 + 12)
route_through_array(image, [0, 0], [1, 1], fully_connected=False, geometric=False)

([(0, 0), (0, 1), (1, 1)], 16.0)

In [7]:
# Larger array where we display the path that is selected
image = np.arange((36)).reshape((6, 6))
image

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
# Find the path with lowest cost
indices, weight = route_through_array(image, (0, 0), (5, 5))
indices = np.array(indices).T
path = np.zeros_like(image)
path[indices[0], indices[1]] = 1
path

array([[1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])